export function generateScript(deviceId, appUrl, os) {
    if (os === 'mac') {
      return `#!/bin/bash
  # ===============================================
  #  Billboard Display Script - macOS
  #  Device ID: ${deviceId}
  #  Generated by Billboard Marketplace
  # ===============================================
  
  APP_URL="${appUrl}"
  DEVICE_ID="${deviceId}"
  PLAYBACK_URL="$APP_URL/playback/$DEVICE_ID"
  
  echo "Starting Billboard Display..."
  echo "URL: $PLAYBACK_URL"
  
  # Wait for internet
  echo "Waiting for internet..."
  until curl -s --head https://google.com | head -n 1 | grep -q "HTTP"; do sleep 3; done
  echo "Internet connected!"
  
  # Kill existing Chrome
  pkill -f "Google Chrome" 2>/dev/null
  sleep 2
  
  # Launch Chrome in kiosk mode
  /Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome \\
    --kiosk \\
    --disable-infobars \\
    --noerrdialogs \\
    --disable-session-crashed-bubble \\
    --disable-component-update \\
    --no-first-run \\
    --start-fullscreen \\
    "$PLAYBACK_URL"
  `;
    }
  
    if (os === 'windows') {
      return `@echo off
  REM ===============================================
  REM  Billboard Display Script - Windows
  REM  Device ID: ${deviceId}
  REM  Generated by Billboard Marketplace
  REM ===============================================
  
  SET APP_URL=${appUrl}
  SET DEVICE_ID=${deviceId}
  SET PLAYBACK_URL=%APP_URL%/playback/%DEVICE_ID%
  
  echo Starting Billboard Display...
  timeout /t 15 /nobreak
  
  taskkill /F /IM chrome.exe 2>nul
  timeout /t 2 /nobreak
  
  start "" "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" ^
    --kiosk ^
    --disable-infobars ^
    --noerrdialogs ^
    --disable-session-crashed-bubble ^
    --no-first-run ^
    --start-fullscreen ^
    "%PLAYBACK_URL%"
  `;
    }
  
    if (os === 'linux') {
      return `#!/bin/bash
  # ===============================================
  #  Billboard Display Script - Linux
  #  Device ID: ${deviceId}
  #  Generated by Billboard Marketplace
  # ===============================================
  
  APP_URL="${appUrl}"
  DEVICE_ID="${deviceId}"
  PLAYBACK_URL="$APP_URL/playback/$DEVICE_ID"
  
  echo "Starting Billboard Display..."
  
  # Wait for internet
  until ping -c1 8.8.8.8 &>/dev/null; do sleep 2; done
  echo "Internet connected!"
  
  # Disable screensaver
  xset s off
  xset -dpms
  xset s noblank
  
  pkill -f chromium 2>/dev/null
  sleep 2
  
  chromium-browser \\
    --kiosk \\
    --disable-infobars \\
    --noerrdialogs \\
    --no-first-run \\
    --start-fullscreen \\
    "$PLAYBACK_URL"
  `;
    }
  }
  
  export function generateAutoStartInstructions(os) {
    if (os === 'mac') {
      return `# Auto-start on Boot - macOS
  
  OPTION 1: Login Items (Easiest)
  1. System Settings -> General -> Login Items
  2. Click + and add billboard-display.sh
  3. Done!
  
  OPTION 2: LaunchAgent (More reliable)
  1. Save this file to:
     ~/Library/LaunchAgents/com.billboard.display.plist
  
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.billboard.display</string>
    <key>ProgramArguments</key>
    <array>
      <string>/bin/bash</string>
      <string>/Users/YOUR_USERNAME/billboard-display.sh</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
  </dict>
  </plist>
  
  2. Run in terminal:
     launchctl load ~/Library/LaunchAgents/com.billboard.display.plist
  
  3. Reboot to test`;
    }
  
    if (os === 'windows') {
      return `# Auto-start on Boot - Windows
  
  OPTION 1: Startup Folder (Easiest)
  1. Press Win+R
  2. Type: shell:startup
  3. Press Enter
  4. Copy billboard-display.bat into that folder
  5. Done - runs on every login!
  
  OPTION 2: Task Scheduler (More reliable)
  1. Open Task Scheduler
  2. Create Basic Task
  3. Name: Billboard Display
  4. Trigger: When the computer starts
  5. Action: Start a program
  6. Browse to billboard-display.bat
  7. Finish`;
    }
  
    if (os === 'linux') {
      return `# Auto-start on Boot - Linux
  
  OPTION 1: Autostart file
  Create: ~/.config/autostart/billboard.desktop
  
  [Desktop Entry]
  Type=Application
  Name=Billboard Display
  Exec=/bin/bash /home/YOUR_USERNAME/billboard-display.sh
  Hidden=false
  X-GNOME-Autostart-enabled=true
  
  OPTION 2: Crontab
  Run: crontab -e
  Add: @reboot sleep 30 && /bin/bash /home/YOUR_USERNAME/billboard-display.sh
  
  OPTION 3: Systemd Service
  Create /etc/systemd/system/billboard.service:
  
  [Unit]
  Description=Billboard Display
  After=network.target
  
  [Service]
  Type=simple
  User=YOUR_USERNAME
  ExecStart=/bin/bash /home/YOUR_USERNAME/billboard-display.sh
  Restart=on-failure
  
  [Install]
  WantedBy=multi-user.target
  
  Then run:
  sudo systemctl enable billboard
  sudo systemctl start billboard`;
    }
  }